export const DIAL_CODES: { code: string; country: string }[] = [
  { code: "+52", country: "México" },
  { code: "+1", country: "Estados Unidos / Canadá" },
  { code: "+54", country: "Argentina" },
  { code: "+591", country: "Bolivia" },
  { code: "+55", country: "Brasil" },
  { code: "+56", country: "Chile" },
  { code: "+57", country: "Colombia" },
  { code: "+506", country: "Costa Rica" },
  { code: "+53", country: "Cuba" },
  { code: "+593", country: "Ecuador" },
  { code: "+503", country: "El Salvador" },
  { code: "+34", country: "España" },
  { code: "+502", country: "Guatemala" },
  { code: "+504", country: "Honduras" },
  { code: "+505", country: "Nicaragua" },
  { code: "+507", country: "Panamá" },
  { code: "+595", country: "Paraguay" },
  { code: "+51", country: "Perú" },
  { code: "+598", country: "Uruguay" },
  { code: "+58", country: "Venezuela" },
  { code: "+33", country: "Francia" },
  { code: "+39", country: "Italia" },
  { code: "+49", country: "Alemania" },
  { code: "+44", country: "Reino Unido" },
  { code: "+351", country: "Portugal" },
  { code: "+31", country: "Países Bajos" },
  { code: "+41", country: "Suiza" },
  { code: "+32", country: "Bélgica" },
  { code: "+46", country: "Suecia" },
  { code: "+47", country: "Noruega" },
  { code: "+45", country: "Dinamarca" },
  { code: "+353", country: "Irlanda" },
  { code: "+30", country: "Grecia" },
  { code: "+81", country: "Japón" },
  { code: "+82", country: "Corea del Sur" },
  { code: "+86", country: "China" },
  { code: "+91", country: "India" },
  { code: "+61", country: "Australia" },
  { code: "+64", country: "Nueva Zelanda" },
  { code: "+27", country: "Sudáfrica" },
  { code: "+971", country: "Emiratos Árabes Unidos" },
  { code: "+972", country: "Israel" },
  { code: "+90", country: "Turquía" },
];
